# Generated by Django 3.1.7 on 2022-06-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0005_auto_20220622_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuplaod',
            name='student',
        ),
    ]
