# Generated by Django 3.1.7 on 2022-06-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0007_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ProjectMessage',
        ),
    ]
