# Generated by Django 3.1.7 on 2022-06-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0008_auto_20220622_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmessage',
            old_name='detail',
            new_name='message',
        ),
    ]
