# Generated by Django 3.1.7 on 2022-06-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0009_auto_20220622_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmessage',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='studentSupervisor.user')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studentSupervisor.projectuplaod')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
