# Generated by Django 3.1.7 on 2022-06-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0012_auto_20220623_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defencecall',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentSupervisor.student'),
        ),
    ]
