# Generated by Django 3.1.7 on 2022-06-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0016_auto_20220623_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuplaod',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentSupervisor.student'),
        ),
        migrations.AddField(
            model_name='projectuplaod',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentSupervisor.supervisor'),
        ),
    ]
