# Generated by Django 3.1.7 on 2022-06-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0018_auto_20220625_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingcomment',
            name='verified_by_supervisor',
        ),
        migrations.AddField(
            model_name='meetingcomment',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('unverified', 'unverified'), ('verified', 'verified')], default='unverified', max_length=255, null=True),
        ),
    ]
