# Generated by Django 3.1.7 on 2022-06-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0020_auto_20220625_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('closed', 'closed')], default='pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectuplaod',
            name='detail',
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
