# Generated by Django 3.1.7 on 2022-06-25 05:34

from django.db import migrations, models
import studentSupervisor.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0021_auto_20220625_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pix',
            field=models.FileField(blank=True, null=True, upload_to=studentSupervisor.models.profile_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('closed', 'closed')], default='ongoing', max_length=255, null=True),
        ),
    ]
