# Generated by Django 3.1.7 on 2022-06-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0023_modelnotifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuplaod',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='datetime',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
