# Generated by Django 3.1.7 on 2022-07-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentSupervisor', '0024_auto_20220629_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('denied', 'denied'), ('closed', 'closed')], default='ongoing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentSupervisor.student'),
        ),
    ]
